version: '3.9'

services:
  webapi:
    container_name: webapicontainer
    build:
      context: .
      dockerfile: Dockerfile_Webapi
    ports:
      - '44310:44310'
      - '44311:44311'
    depends_on:
      - "rabbitmq"

  rabbitmq:
    container_name: "rabbitmqcontainer"
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
        - '5672:5672'
        - '15672:15672'

  consumer:
    container_name: consumercontainer
    build:
      context: .
      dockerfile: Dockerfile_Consumer
    depends_on:
      - "rabbitmq"

  consumer2:
    container_name: consumer2container
    build:
      context: .
      dockerfile: Dockerfile_Consumer2
    depends_on:
      - "rabbitmq"