FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 44310
EXPOSE 44311

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Webapi/Webapi.csproj", "Webapi/"]
COPY ["Shared/Shared.csproj", "Shared/"]
RUN dotnet restore "Webapi/Webapi.csproj"
COPY ["Webapi/", "Webapi/"]
COPY ["Shared/", "Shared/"]
WORKDIR "/src/Webapi"
RUN dotnet build "Webapi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Webapi.csproj" -c $BUILD_CONFIGURATION -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "Webapi.dll" ]